typedef struct { 	double *  inoutE1 ;
	double *  inB0 ;
	int *  xoffset ;
	int *  yoffset ;
	int *  zoffset ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  DT ;
	double *  DELTA_Z ;
	double *  DELTA_Y ;
	double *  DELTA_X ;
	double *  x0 ;
	long  inoutE1_len ;
	long  inB0_len ;
	long  xoffset_len ;
	long  yoffset_len ;
	long  zoffset_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  DT_len ;
	long  DELTA_Z_len ;
	long  DELTA_Y_len ;
	long  DELTA_X_len ;
	long  x0_len ;
} c_GEO_YEE_CURL_L_struct;void  c_GEO_YEE_CURL_L_scmc_kernel (double *  inoutE1 ,double *  inB0 ,int *  xoffset ,int *  yoffset ,int *  zoffset ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  DT ,double  DELTA_Z ,double  DELTA_Y ,double  DELTA_X ,double  x0 ,long  yid_kernel ,long  ylen_kernel );
