void  c_hydro_push_rho_s_scmc_kernel (double *  out_rho_s_vx ,double *  alpha_beta_new ,double *  alpha_beta ,double *  rho_s_vx ,double *  vA ,double *  vAzero ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,int  num_ele_rho_s_vx ,int  num_ele_vA ,int  num_ele_alpha_beta ,double  QM0 ,double  U0 ,double  DX ,double  DY ,double  DZ ,double  DT ,long  scmc_internal_g_idy ,long  scmc_internal_g_ylen )
;
void  c_hydro_push_vx_scmc_kernel (double *  out_rho_s_vx ,double *  alpha_beta_new ,double *  alpha_beta ,double *  rho_s_vx ,double *  vA ,double *  vAzero ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,int  num_ele_rho_s_vx ,int  num_ele_vA ,int  num_ele_alpha_beta ,double  QM0 ,double  U0 ,double  DX ,double  DY ,double  DZ ,double  DT ,long  scmc_internal_g_idy ,long  scmc_internal_g_ylen )
;
void  c_hydro_push_alpha_beta_scmc_kernel (double *  out_alpha_beta ,double *  alpha_beta_new ,double *  alpha_beta ,double *  rho_s_vx ,double *  vA ,double *  vAzero ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,int  num_ele_rho_s_vx ,int  num_ele_vA ,int  num_ele_alpha_beta ,double  QM0 ,double  U0 ,double  DX ,double  DY ,double  DZ ,double  DT ,long  scmc_internal_g_idy ,long  scmc_internal_g_ylen )
;
void  c_hydro_push_jac_alpha_beta_scmc_kernel (double *  out_alpha_beta ,double *  alpha_beta_new ,double *  alpha_beta ,double *  rho_s_vx ,double *  vA ,double *  vAzero ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,int  num_ele_rho_s_vx ,int  num_ele_vA ,int  num_ele_alpha_beta ,double  QM0 ,double  U0 ,double  DX ,double  DY ,double  DZ ,double  DT ,long  scmc_internal_g_idy ,long  scmc_internal_g_ylen )
;
void  c_hydro_push_vA_scmc_kernel (double *  out_vA ,double *  alpha_beta_new ,double *  alpha_beta ,double *  rho_s_vx ,double *  vA ,double *  vAzero ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,int  num_ele_rho_s_vx ,int  num_ele_vA ,int  num_ele_alpha_beta ,double  QM0 ,double  U0 ,double  DX ,double  DY ,double  DZ ,double  DT ,long  scmc_internal_g_idy ,long  scmc_internal_g_ylen )
;
