typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_setfix_xyz_struct;void  c_yee_setfix_xyz_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_damp_xyz_struct;void  c_yee_damp_xyz_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_pec_xyz_struct;void  c_yee_pec_xyz_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_abc_xyz_struct;void  c_yee_abc_xyz_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_setfix_yz_struct;void  c_yee_setfix_yz_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_damp_yz_struct;void  c_yee_damp_yz_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_pec_yz_struct;void  c_yee_pec_yz_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_abc_yz_struct;void  c_yee_abc_yz_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_setfix_xz_struct;void  c_yee_setfix_xz_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_damp_xz_struct;void  c_yee_damp_xz_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_pec_xz_struct;void  c_yee_pec_xz_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_abc_xz_struct;void  c_yee_abc_xz_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_setfix_xy_struct;void  c_yee_setfix_xy_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_damp_xy_struct;void  c_yee_damp_xy_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_pec_xy_struct;void  c_yee_pec_xy_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_abc_xy_struct;void  c_yee_abc_xy_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_setfix_z_struct;void  c_yee_setfix_z_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_damp_z_struct;void  c_yee_damp_z_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_pec_z_struct;void  c_yee_pec_z_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_abc_z_struct;void  c_yee_abc_z_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_setfix_y_struct;void  c_yee_setfix_y_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_damp_y_struct;void  c_yee_damp_y_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_pec_y_struct;void  c_yee_pec_y_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_abc_y_struct;void  c_yee_abc_y_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_setfix_x_struct;void  c_yee_setfix_x_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_damp_x_struct;void  c_yee_damp_x_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_pec_x_struct;void  c_yee_pec_x_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_abc_x_struct;void  c_yee_abc_x_scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_setfix__struct;void  c_yee_setfix__scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_damp__struct;void  c_yee_damp__scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_pec__struct;void  c_yee_pec__scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  outEB ;
	double *  inEB ;
	int *  cur_rankx ;
	int *  cur_ranky ;
	int *  cur_rankz ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	double *  damp_vars ;
	double *  deltat ;
	long  outEB_len ;
	long  inEB_len ;
	long  cur_rankx_len ;
	long  cur_ranky_len ;
	long  cur_rankz_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  damp_vars_len ;
	long  deltat_len ;
} c_yee_abc__struct;void  c_yee_abc__scmc_kernel (double *  outEB ,double *  inEB ,int *  cur_rankx ,int *  cur_ranky ,int *  cur_rankz ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,double  damp_vars ,double  deltat ,long  yid_kernel ,long  ylen_kernel );
