typedef struct { 	double *  phi_out ;
	double *  phi_in ;
	double *  phi_1 ;
	double *  A1 ;
	double *  A2 ;
	double *  A3 ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	int *  num_ele_A1 ;
	double *  DT ;
	double *  M ;
	double *  Q ;
	double *  DM_A ;
	long  phi_out_len ;
	long  phi_in_len ;
	long  phi_1_len ;
	long  A1_len ;
	long  A2_len ;
	long  A3_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  num_ele_A1_len ;
	long  DT_len ;
	long  M_len ;
	long  Q_len ;
	long  DM_A_len ;
} openmp_dm_1st_eqn_right_struct;void  openmp_dm_1st_eqn_right_scmc_kernel (double *  phi_out ,double *  phi_in ,double *  phi_1 ,double *  A1 ,double *  A2 ,double *  A3 ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,int  num_ele_A1 ,double  DT ,double  M ,double  Q ,double  DM_A ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  phi_out ;
	double *  phi_in ;
	double *  phi_1 ;
	double *  A1 ;
	double *  A2 ;
	double *  A3 ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	int *  num_ele_A1 ;
	double *  DT ;
	double *  M ;
	double *  Q ;
	double *  DM_A ;
	long  phi_out_len ;
	long  phi_in_len ;
	long  phi_1_len ;
	long  A1_len ;
	long  A2_len ;
	long  A3_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  num_ele_A1_len ;
	long  DT_len ;
	long  M_len ;
	long  Q_len ;
	long  DM_A_len ;
} openmp_dm_1st_eqn_core_struct;void  openmp_dm_1st_eqn_core_scmc_kernel (double *  phi_out ,double *  phi_in ,double *  phi_1 ,double *  A1 ,double *  A2 ,double *  A3 ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,int  num_ele_A1 ,double  DT ,double  M ,double  Q ,double  DM_A ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  phi_out ;
	double *  phi_in ;
	double *  phi_1 ;
	double *  A1 ;
	double *  A2 ;
	double *  A3 ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	int *  num_ele_A1 ;
	double *  DT ;
	double *  M ;
	double *  Q ;
	double *  DM_A ;
	long  phi_out_len ;
	long  phi_in_len ;
	long  phi_1_len ;
	long  A1_len ;
	long  A2_len ;
	long  A3_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  num_ele_A1_len ;
	long  DT_len ;
	long  M_len ;
	long  Q_len ;
	long  DM_A_len ;
} openmp_dm_1st_eqn_fdtd_struct;void  openmp_dm_1st_eqn_fdtd_scmc_kernel (double *  phi_out ,double *  phi_in ,double *  phi_1 ,double *  A1 ,double *  A2 ,double *  A3 ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,int  num_ele_A1 ,double  DT ,double  M ,double  Q ,double  DM_A ,long  yid_kernel ,long  ylen_kernel );
