typedef struct { 	double *  dphi_dt_out ;
	double *  phi_in ;
	double *  A1 ;
	double *  Y1 ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	int *  num_ele_A1 ;
	double *  M ;
	double *  Q ;
	double *  DM_A ;
	double *  DX ;
	double *  DY ;
	double *  DZ ;
	double *  DT ;
	long  dphi_dt_out_len ;
	long  phi_in_len ;
	long  A1_len ;
	long  Y1_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  num_ele_A1_len ;
	long  M_len ;
	long  Q_len ;
	long  DM_A_len ;
	long  DX_len ;
	long  DY_len ;
	long  DZ_len ;
	long  DT_len ;
} openmp_dm_calc_hamt_dual_struct;void  openmp_dm_calc_hamt_dual_scmc_kernel (double *  dphi_dt_out ,double *  phi_in ,double *  A1 ,double *  Y1 ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,int  num_ele_A1 ,double  M ,double  Q ,double  DM_A ,double  DX ,double  DY ,double  DZ ,double  DT ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  dphi_dt_out ;
	double *  phi_in ;
	double *  A1 ;
	double *  Y1 ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	int *  num_ele_A1 ;
	double *  M ;
	double *  Q ;
	double *  DM_A ;
	double *  DX ;
	double *  DY ;
	double *  DZ ;
	double *  DT ;
	long  dphi_dt_out_len ;
	long  phi_in_len ;
	long  A1_len ;
	long  Y1_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  num_ele_A1_len ;
	long  M_len ;
	long  Q_len ;
	long  DM_A_len ;
	long  DX_len ;
	long  DY_len ;
	long  DZ_len ;
	long  DT_len ;
} openmp_dm_cayley_eqn_core_struct;void  openmp_dm_cayley_eqn_core_scmc_kernel (double *  dphi_dt_out ,double *  phi_in ,double *  A1 ,double *  Y1 ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,int  num_ele_A1 ,double  M ,double  Q ,double  DM_A ,double  DX ,double  DY ,double  DZ ,double  DT ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  dphi_dt_out ;
	double *  phi_in ;
	double *  A1 ;
	double *  Y1 ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	int *  num_ele_A1 ;
	double *  M ;
	double *  Q ;
	double *  DM_A ;
	double *  DX ;
	double *  DY ;
	double *  DZ ;
	double *  DT ;
	long  dphi_dt_out_len ;
	long  phi_in_len ;
	long  A1_len ;
	long  Y1_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  num_ele_A1_len ;
	long  M_len ;
	long  Q_len ;
	long  DM_A_len ;
	long  DX_len ;
	long  DY_len ;
	long  DZ_len ;
	long  DT_len ;
} openmp_dm_exact_eqn_m_struct;void  openmp_dm_exact_eqn_m_scmc_kernel (double *  dphi_dt_out ,double *  phi_in ,double *  A1 ,double *  Y1 ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,int  num_ele_A1 ,double  M ,double  Q ,double  DM_A ,double  DX ,double  DY ,double  DZ ,double  DT ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  dphi_dt_out ;
	double *  phi_in ;
	double *  A1 ;
	double *  Y1 ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	int *  num_ele_A1 ;
	double *  M ;
	double *  Q ;
	double *  DM_A ;
	double *  DX ;
	double *  DY ;
	double *  DZ ;
	double *  DT ;
	long  dphi_dt_out_len ;
	long  phi_in_len ;
	long  A1_len ;
	long  Y1_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  num_ele_A1_len ;
	long  M_len ;
	long  Q_len ;
	long  DM_A_len ;
	long  DX_len ;
	long  DY_len ;
	long  DZ_len ;
	long  DT_len ;
} openmp_dm_calc_hamt_struct;void  openmp_dm_calc_hamt_scmc_kernel (double *  dphi_dt_out ,double *  phi_in ,double *  A1 ,double *  Y1 ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,int  num_ele_A1 ,double  M ,double  Q ,double  DM_A ,double  DX ,double  DY ,double  DZ ,double  DT ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  dphi_dt_out ;
	double *  phi_in ;
	double *  A1 ;
	double *  Y1 ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	int *  num_ele_A1 ;
	double *  M ;
	double *  Q ;
	double *  DM_A ;
	double *  DX ;
	double *  DY ;
	double *  DZ ;
	double *  DT ;
	long  dphi_dt_out_len ;
	long  phi_in_len ;
	long  A1_len ;
	long  Y1_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  num_ele_A1_len ;
	long  M_len ;
	long  Q_len ;
	long  DM_A_len ;
	long  DX_len ;
	long  DY_len ;
	long  DZ_len ;
	long  DT_len ;
} openmp_dm_cayley_eqn_J_struct;void  openmp_dm_cayley_eqn_J_scmc_kernel (double *  dphi_dt_out ,double *  phi_in ,double *  A1 ,double *  Y1 ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,int  num_ele_A1 ,double  M ,double  Q ,double  DM_A ,double  DX ,double  DY ,double  DZ ,double  DT ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  dphi_dt_out ;
	double *  phi_in ;
	double *  A1 ;
	double *  Y1 ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	int *  num_ele_A1 ;
	double *  M ;
	double *  Q ;
	double *  DM_A ;
	double *  DX ;
	double *  DY ;
	double *  DZ ;
	double *  DT ;
	long  dphi_dt_out_len ;
	long  phi_in_len ;
	long  A1_len ;
	long  Y1_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  num_ele_A1_len ;
	long  M_len ;
	long  Q_len ;
	long  DM_A_len ;
	long  DX_len ;
	long  DY_len ;
	long  DZ_len ;
	long  DT_len ;
} openmp_dm_bihamt_eqn_dydt_struct;void  openmp_dm_bihamt_eqn_dydt_scmc_kernel (double *  dphi_dt_out ,double *  phi_in ,double *  A1 ,double *  Y1 ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,int  num_ele_A1 ,double  M ,double  Q ,double  DM_A ,double  DX ,double  DY ,double  DZ ,double  DT ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  dphi_dt_out ;
	double *  phi_in ;
	double *  A1 ;
	double *  Y1 ;
	long *  y_cpu_core ;
	long *  numvec ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  num_ele ;
	int *  num_ele_A1 ;
	double *  M ;
	double *  Q ;
	double *  DM_A ;
	double *  DX ;
	double *  DY ;
	double *  DZ ;
	double *  DT ;
	long  dphi_dt_out_len ;
	long  phi_in_len ;
	long  A1_len ;
	long  Y1_len ;
	long  y_cpu_core_len ;
	long  numvec_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  num_ele_len ;
	long  num_ele_A1_len ;
	long  M_len ;
	long  Q_len ;
	long  DM_A_len ;
	long  DX_len ;
	long  DY_len ;
	long  DZ_len ;
	long  DT_len ;
} openmp_dm_bihamt_dual_psi_eqn_J_struct;void  openmp_dm_bihamt_dual_psi_eqn_J_scmc_kernel (double *  dphi_dt_out ,double *  phi_in ,double *  A1 ,double *  Y1 ,long  y_cpu_core ,long  numvec ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  xblock ,long  yblock ,long  zblock ,int  num_ele ,int  num_ele_A1 ,double  M ,double  Q ,double  DM_A ,double  DX ,double  DY ,double  DZ ,double  DT ,long  yid_kernel ,long  ylen_kernel );
