typedef struct { 	double *  cu_cache ;
	int *  cu_xyzw ;
	long *  adjoint_vec_pids ;
	long *  cu_cache_length ;
	int *  the_dir_num ;
	long *  XYZLEN ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  adjoint_vec_pids_len ;
	long  cu_cache_length_len ;
	long  the_dir_num_len ;
	long  XYZLEN_len ;
} openmp_cu_swap_r_struct;void  openmp_cu_swap_r_scmc_kernel (double *  cu_cache ,int *  cu_xyzw ,long *  adjoint_vec_pids ,long  cu_cache_length ,int  the_dir_num ,long  XYZLEN ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  cu_cache ;
	int *  cu_xyzw ;
	long *  adjoint_vec_pids ;
	long *  cu_cache_length ;
	int *  the_dir_num ;
	long *  XYZLEN ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  adjoint_vec_pids_len ;
	long  cu_cache_length_len ;
	long  the_dir_num_len ;
	long  XYZLEN_len ;
} openmp_cu_swap_l_struct;void  openmp_cu_swap_l_scmc_kernel (double *  cu_cache ,int *  cu_xyzw ,long *  adjoint_vec_pids ,long  cu_cache_length ,int  the_dir_num ,long  XYZLEN ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	long *  adjoint_vec_pids ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  adjoint_vec_pids_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
} openmp_sort_one_grid_z_vlo_struct;void  openmp_sort_one_grid_z_vlo_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,long *  adjoint_vec_pids ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,long  grid_cache_len ,long  cu_cache_length ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	long *  adjoint_vec_pids ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  adjoint_vec_pids_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
} openmp_sort_one_grid_y_vlo_struct;void  openmp_sort_one_grid_y_vlo_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,long *  adjoint_vec_pids ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,long  grid_cache_len ,long  cu_cache_length ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	long *  adjoint_vec_pids ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  adjoint_vec_pids_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
} openmp_sort_one_grid_x_vlo_struct;void  openmp_sort_one_grid_x_vlo_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,long *  adjoint_vec_pids ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,long  grid_cache_len ,long  cu_cache_length ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	long *  adjoint_vec_pids ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  adjoint_vec_pids_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
} openmp_sort_one_grid_z_struct;void  openmp_sort_one_grid_z_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,long *  adjoint_vec_pids ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,long  grid_cache_len ,long  cu_cache_length ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	long *  adjoint_vec_pids ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  adjoint_vec_pids_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
} openmp_sort_one_grid_y_struct;void  openmp_sort_one_grid_y_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,long *  adjoint_vec_pids ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,long  grid_cache_len ,long  cu_cache_length ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	long *  adjoint_vec_pids ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  adjoint_vec_pids_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
} openmp_sort_one_grid_x_struct;void  openmp_sort_one_grid_x_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,long *  adjoint_vec_pids ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,long  grid_cache_len ,long  cu_cache_length ,long  yid_kernel ,long  ylen_kernel );
