typedef struct { 	double *  vecmain ;
	double *  vecovlp ;
	int *  ovlpindex ;
	long *  numvec ;
	int *  num_ele ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  ovlp ;
	long  vecmain_len ;
	long  vecovlp_len ;
	long  ovlpindex_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  ovlp_len ;
} openmp_merge_ovlp_m2o_struct;void  openmp_merge_ovlp_m2o_scmc_kernel (double *  vecmain ,double *  vecovlp ,int  ovlpindex ,long  numvec ,int  num_ele ,long  xblock ,long  yblock ,long  zblock ,int  ovlp ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  vecmain ;
	double *  vecovlp ;
	int *  ovlpindex ;
	long *  numvec ;
	int *  num_ele ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  ovlp ;
	long  vecmain_len ;
	long  vecovlp_len ;
	long  ovlpindex_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  ovlp_len ;
} openmp_merge_ovlp_o2m_struct;void  openmp_merge_ovlp_o2m_scmc_kernel (double *  vecmain ,double *  vecovlp ,int  ovlpindex ,long  numvec ,int  num_ele ,long  xblock ,long  yblock ,long  zblock ,int  ovlp ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  vecmain ;
	double *  vecovlp ;
	int *  ovlpindex ;
	long *  numvec ;
	int *  num_ele ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  ovlp ;
	long  vecmain_len ;
	long  vecovlp_len ;
	long  ovlpindex_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  ovlp_len ;
} openmp_sync_ovlp_m2o_struct;void  openmp_sync_ovlp_m2o_scmc_kernel (double *  vecmain ,double *  vecovlp ,int  ovlpindex ,long  numvec ,int  num_ele ,long  xblock ,long  yblock ,long  zblock ,int  ovlp ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  vecmain ;
	double *  vecovlp ;
	int *  ovlpindex ;
	long *  numvec ;
	int *  num_ele ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  ovlp ;
	long  vecmain_len ;
	long  vecovlp_len ;
	long  ovlpindex_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  ovlp_len ;
} openmp_sync_ovlp_o2m_struct;void  openmp_sync_ovlp_o2m_scmc_kernel (double *  vecmain ,double *  vecovlp ,int  ovlpindex ,long  numvec ,int  num_ele ,long  xblock ,long  yblock ,long  zblock ,int  ovlp ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inout ;
	long *  numvec ;
	int *  num_ele ;
	long *  xblock ;
	long *  yblock ;
	long *  zblock ;
	int *  ovlp ;
	long  inout_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  xblock_len ;
	long  yblock_len ;
	long  zblock_len ;
	long  ovlp_len ;
} openmp_yee_local_struct;void  openmp_yee_local_scmc_kernel (double *  inout ,long  numvec ,int  num_ele ,long  xblock ,long  yblock ,long  zblock ,int  ovlp ,long  yid_kernel ,long  ylen_kernel );
