typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
} openmp_move_back_kernel_struct;void  openmp_move_back_kernel_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,long  XLEN ,long  YLEN ,long  ZLEN ,long  grid_cache_len ,long  cu_cache_length ,long  yid_kernel ,long  ylen_kernel );
