typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  FoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  FoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_dump_ene_num_struct;void  openmp_dump_ene_num_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  FoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  FoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  FoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_calculate_rho_struct;void  openmp_calculate_rho_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  FoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  FoutJ ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass0 ;
	double *  Charge0 ;
	double *  Deltat ;
	double *  mu_freq ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  FoutJ_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass0_len ;
	long  Charge0_len ;
	long  Deltat_len ;
	long  mu_freq_len ;
} openmp_krook_collision_test_struct;void  openmp_krook_collision_test_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  FoutJ ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass0 ,double  Charge0 ,double  Deltat ,double  mu_freq ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  FoutJ ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass0 ;
	double *  Charge0 ;
	double *  Deltat ;
	double *  mu_freq ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  FoutJ_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass0_len ;
	long  Charge0_len ;
	long  Deltat_len ;
	long  mu_freq_len ;
} openmp_krook_collision_remove_small_speed_struct;void  openmp_krook_collision_remove_small_speed_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  FoutJ ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass0 ,double  Charge0 ,double  Deltat ,double  mu_freq ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  FoutJ ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass0 ;
	double *  Charge0 ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  FoutJ_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass0_len ;
	long  Charge0_len ;
	long  Deltat_len ;
} openmp_boris_yee_struct;void  openmp_boris_yee_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  FoutJ ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass0 ,double  Charge0 ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  FoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  FoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_E_particle_vlo_struct;void  openmp_split_pass_E_particle_vlo_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  FoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  FoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  FoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_E_particle_struct;void  openmp_split_pass_E_particle_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  FoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  LFoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  LFoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_z_vlo_sg2_nopush_small_grids_struct;void  openmp_split_pass_z_vlo_sg2_nopush_small_grids_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  LFoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  LFoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  LFoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_z_vlo_sg2_small_grids_struct;void  openmp_split_pass_z_vlo_sg2_small_grids_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  LFoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  LFoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  LFoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_z_vlo_small_grids_struct;void  openmp_split_pass_z_vlo_small_grids_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  LFoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  LFoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  LFoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_z_sg2_small_grids_struct;void  openmp_split_pass_z_sg2_small_grids_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  LFoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  LFoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  LFoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_z_small_grids_struct;void  openmp_split_pass_z_small_grids_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  LFoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  FoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  FoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_z_vlo_nopush_struct;void  openmp_split_pass_z_vlo_nopush_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  FoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  FoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  FoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_z_vlo_struct;void  openmp_split_pass_z_vlo_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  FoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  FoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  FoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_z_nopush_struct;void  openmp_split_pass_z_nopush_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  FoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  FoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  FoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_z_struct;void  openmp_split_pass_z_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  FoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  LFoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  LFoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_y_vlo_sg2_nopush_small_grids_struct;void  openmp_split_pass_y_vlo_sg2_nopush_small_grids_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  LFoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  LFoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  LFoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_y_vlo_sg2_small_grids_struct;void  openmp_split_pass_y_vlo_sg2_small_grids_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  LFoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  LFoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  LFoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_y_vlo_small_grids_struct;void  openmp_split_pass_y_vlo_small_grids_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  LFoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  LFoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  LFoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_y_sg2_small_grids_struct;void  openmp_split_pass_y_sg2_small_grids_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  LFoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  LFoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  LFoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_y_small_grids_struct;void  openmp_split_pass_y_small_grids_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  LFoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  FoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  FoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_y_vlo_nopush_struct;void  openmp_split_pass_y_vlo_nopush_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  FoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  FoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  FoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_y_vlo_struct;void  openmp_split_pass_y_vlo_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  FoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  FoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  FoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_y_nopush_struct;void  openmp_split_pass_y_nopush_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  FoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  FoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  FoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_y_struct;void  openmp_split_pass_y_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  FoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  LFoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  LFoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_x_vlo_sg2_nopush_small_grids_struct;void  openmp_split_pass_x_vlo_sg2_nopush_small_grids_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  LFoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  LFoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  LFoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_x_vlo_sg2_small_grids_struct;void  openmp_split_pass_x_vlo_sg2_small_grids_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  LFoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  LFoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  LFoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_x_vlo_small_grids_struct;void  openmp_split_pass_x_vlo_small_grids_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  LFoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  LFoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  LFoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_x_sg2_small_grids_struct;void  openmp_split_pass_x_sg2_small_grids_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  LFoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  LFoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  LFoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_x_small_grids_struct;void  openmp_split_pass_x_small_grids_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  LFoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  FoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  FoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_x_vlo_nopush_struct;void  openmp_split_pass_x_vlo_nopush_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  FoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  FoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  FoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_x_vlo_struct;void  openmp_split_pass_x_vlo_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  FoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  FoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  FoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_x_nopush_struct;void  openmp_split_pass_x_nopush_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  FoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
typedef struct { 	double *  inoutput ;
	int *  xyzw ;
	double *  cu_cache ;
	int *  cu_xyzw ;
	double *  fieldE ;
	double *  fieldB ;
	double *  FoutJ ;
	double *  FoutEN ;
	long *  XLEN ;
	long *  YLEN ;
	long *  ZLEN ;
	int *  ovlp ;
	long *  numvec ;
	int *  num_ele ;
	long *  grid_cache_len ;
	long *  cu_cache_length ;
	double *  Mass ;
	double *  Charge ;
	int *  SPEC ;
	int *  NUM_SPEC ;
	double *  DELTA_X ;
	double *  DELTA_Y ;
	double *  DELTA_Z ;
	double *  Deltat ;
	long  inoutput_len ;
	long  xyzw_len ;
	long  cu_cache_len ;
	long  cu_xyzw_len ;
	long  fieldE_len ;
	long  fieldB_len ;
	long  FoutJ_len ;
	long  FoutEN_len ;
	long  XLEN_len ;
	long  YLEN_len ;
	long  ZLEN_len ;
	long  ovlp_len ;
	long  numvec_len ;
	long  num_ele_len ;
	long  grid_cache_len_len ;
	long  cu_cache_length_len ;
	long  Mass_len ;
	long  Charge_len ;
	long  SPEC_len ;
	long  NUM_SPEC_len ;
	long  DELTA_X_len ;
	long  DELTA_Y_len ;
	long  DELTA_Z_len ;
	long  Deltat_len ;
} openmp_split_pass_x_struct;void  openmp_split_pass_x_scmc_kernel (double *  inoutput ,int *  xyzw ,double *  cu_cache ,int *  cu_xyzw ,double *  fieldE ,double *  fieldB ,double *  FoutJ ,double *  FoutEN ,long  XLEN ,long  YLEN ,long  ZLEN ,int  ovlp ,long  numvec ,int  num_ele ,long  grid_cache_len ,long  cu_cache_length ,double  Mass ,double  Charge ,int  SPEC ,int  NUM_SPEC ,double  DELTA_X ,double  DELTA_Y ,double  DELTA_Z ,double  Deltat ,long  yid_kernel ,long  ylen_kernel );
